### ISSUE TITLE
CSS styles are broken on the blog

### ISSUE THREAD

**Issue by amitness** [nicoddemus/nicoddemus.github.io#2]
I was reading an article on your blog and the styles didn't load. The browser used was Chrome. I think it's because your site has https enabled but the CSS styles still point to HTTP versions and chrome blocks the loading of styles.

![image](https://user-images.githubusercontent.com/8587189/50040527-4aed1f00-006d-11e9-8664-71073874a911.png)

**Comment by nicoddemus** [comment]
Thanks for the report @amitness! I will look into it.

**Comment by nicoddemus** [comment]
Hi @amitness,

Weird, the site looks fine to me (also on Chrome):

![image](https://user-images.githubusercontent.com/1085180/50182164-be08c680-02f5-11e9-8e7d-afa70227d74d.png)

I see an error about disqus still using `HTTP`, but that's a problem with the specific theme I'm using. Not sure why you are seeing an old version of the site...

**Comment by amitness** [comment]
@amitness Looks like the update from http to https in the configuration made it work. It's fine now.
